#!/bin/sh

case $1 in
    start)
        mode="664"

        set -e
        # Group: since distributions do it differently, look for wheel or use staff
        # These are groups which correspond to system administrator accounts
        if grep -q '^staff:' /etc/group; then
            group="staff"
        else
            group="wheel"
        fi

        echo "Load our module, exit on failure"

        for i in "hello" "faulty"; do
            module=$i
            device=$i
            modprobe $module || exit 1
            echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
            major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
            if [ ! -z ${major} ]; then
                echo "Remove any existing /dev node for /dev/${device}"
                rm -f /dev/${device}
                echo "Add a node for our device at /dev/${device} using mknod"
                mknod /dev/${device} c $major 0
                echo "Change group owner to ${group}"
                chgrp $group /dev/${device}
                echo "Change access mode to ${mode}"
                chmod $mode  /dev/${device}
            else
                echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)"
            fi
        done
        ;;
    stop)
        for i in "hello" "faulty"; do
            module=$i
            device=$i

            if [ $# -ne 1 ]; then
                echo "Wrong number of arguments"
                echo "usage: $0 module_name"
                echo "Will unload the module specified by module_name and remove assocaited device"
                exit 1
            fi

            # invoke rmmod with all arguments we got
            rmmod $module || exit 1

            # Remove stale nodes

            rm -f /dev/${device}
        done
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0